# production only prints info and above. development also prints debug
environment: production
eth_rpc_url: https://ethereum-holesky-rpc.publicnode.com
eth_ws_url: wss://ethereum-holesky-rpc.publicnode.com
# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: 0.0.0.0:4001
aggregator_rest_server_ip_port_address: 0.0.0.0:4002
aggregator_database_path: "./db"
aggregator_checkpoint_interval: 3600000 # ms
rollup_ids_to_rpc_urls:
  421614: wss://arbitrum-sepolia-rpc.publicnode.com
  11155420: wss://optimism-sepolia-rpc.publicnode.com
rollup_ids_to_registry_addresses:
  421614: 0x6eB9b1FAdCEE1a722B3bCf82c14b6C0067a7f123
  11155420: 0x6eB9b1FAdCEE1a722B3bCf82c14b6C0067a7f123
