version: "3"

services:
  aggregator:
    image: ghcr.io/nethermindeth/near-sffl/aggregator:${SFFL_RELEASE}
    container_name: near-sffl-aggregator
    volumes:
      - ./:/near-sffl/
    working_dir: /near-sffl
    command: 
      - --config 
      - config/aggregator.yaml
      - --sffl-deployment 
      - config/deployment/17000.json
      - --ecdsa-private-key 
      - ${ECDSA_PRIVATE_KEY}
      - --rollup-configs
      - config/deployment/421614.json
      - --rollup-configs
      - config/deployment/11155420.json
    expose:
      - 4001
      - 4002
