name: Build and Push Containers

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout"
        type: string
        required: true
        default: "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nethermindeth/near-sffl

jobs:
  custom-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./indexer/Dockerfile
            image: indexer
          - dockerfile: ./relayer/Dockerfile  
            image: relayer
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: >-
            image=moby/buildkit:master

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}
            type=sha
            type=ref,event=branch
            type=ref,event=tag
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  ko:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: aggregator/cmd/main.go
            image: aggregator
          - path: operator/cmd/main.go
            image: operator
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=semver,pattern={{version}}
            type=sha
            type=ref,event=branch
            type=ref,event=tag
          sep-tags: ","
      
      - name: Set up Ko
        uses: ko-build/setup-ko@v0.6
      
      - name: Build and push container
        run: ko build ${{ matrix.path }} --bare --tags=${{ steps.meta.outputs.tags }}
        env:
          KO_DOCKER_REPO: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}
