name: Build and Push Containers

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Specific Commit SHA (Required)"
        required: true
      release_tag:
        description: "Release Tag (Optional)"
        required: false
        default: ""

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nethermindeth/near-sffl

jobs:
  custom-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./indexer/Dockerfile
            image: indexer
          - dockerfile: ./relayer/Dockerfile  
            image: relayer
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: >-
            image=moby/buildkit:master

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Tag Name
        id: set_tag
        run: echo "tag=${{ github.event.inputs.release_tag || github.event.inputs.commit_sha }}" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=,enable=true
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false # dry-run
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}:${{ steps.set_tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
  
  ko:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: aggregator/cmd/main.go
            image: aggregator
          - path: operator/cmd/main.go
            image: operator
          - path: plugin/cmd/main.go
            image: operator-plugin
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'

      - name: Set Tag Name
        id: set_tag
        run: echo "tag=${{ github.event.inputs.release_tag || github.event.inputs.commit_sha }}" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=,enable=true
      
      - name: Set up Ko
        uses: ko-build/setup-ko@v0.6
      
      - name: Build and push container
        run: ko build ${{ matrix.path }} --bare --tags=${{ steps.set_tag.outputs.tag }} --push false # dry-run
        env:
          KO_DOCKER_REPO: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image }}
