name: License check

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check_cargo_deny:
    name: "Cargo Deny"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@2.34.1
        with:
          tool: cargo-deny@0.14.24
      - run: cargo deny --all-features --locked check bans
