name: License check

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check_cargo_deny:
    name: "Cargo Deny"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@91af8c38814c3998cb755869e5cbeffd3ab0e462
        with:
          tool: cargo-deny
      - run: cargo deny --all-features --locked check bans
