
name: integration-tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:  
  Test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 70

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build indexer container
        run: docker build -t near-sffl-indexer -f ./indexer/Dockerfile .

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./contracts/evm
        
      - name: Install near-cli
        run: npm i -g near-cli@3.5.0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        run: forge install
        working-directory: ./contracts/evm

      - name: Test
        run: make tests-integration
